### ISSUE TITLE
Use group constraint in mvPortfolio

### ISSUE THREAD

**Issue by clcsar** [enricoschumann/NMOF#2]
I am trying to use mvPortfolio with groups. I have a list of 7 assets which I have min/max weights for each. The way I did was to include the following in mvPortfolio call
 groups = list of 7 asset names
 groups.wmin = vector of 7 numeric numbers
 groups.wmax = vector of 7 numeric numbers

and the error message I got was
Error in quadprog::solve.QP(Dmat = Q, dvec = if (is.null(lambda)) rep(0,  : 
  Amat and bvec are incompatible!
In addition: Warning message:
In rbind(bvec, Groups$b.ineq) :
  number of columns of result is not a multiple of vector length (arg 2)

Without group constraints mvPortfolio seems to work fine. Thanks.

**Comment by enricoschumann** [comment]
This is a bug in how the constraints matrices are set up; thanks for the report.
I just pushed a change. With this, you should be able to use group constraints:
```r
    library("NMOF")

    ## create random data
    na <- 7   ## number of assets
    ns <- 50  ## number of scenarios
    R  <- randomReturns(na = na, ns = ns, sd = 0.02, mean = 0)
    
    ## variant 1: groups are defined by positions. The first asset specifies one group, and
    ##            assets 4 and 5 are in one group
    sol1 <- mvPortfolio(m = colMeans(R), var = cov(R),
                       min.return = 0,
                       groups = list(1, 4:5),
                       groups.wmin = c(0.25, 0.1),
                       groups.wmax = c(0.30, 0.2))

    ## variant 2: groups are defined by labels. Now all assets must receive a label
    ##            (i.e. 'groups' is of length 'na')
    sol2 <- mvPortfolio(m = colMeans(R), var = cov(R),
                       min.return = 0,
                       groups = c("A", "none", "none", "B", "B", "none", "none"),
                       groups.wmin = c(A = 0.25, B = 0.1),
                       groups.wmax = c(A = 0.30, B = 0.2))

Would you test these changes, please?

**Comment by clcsar** [comment]
Pulled the latest (2.2) and group constraints work fine now. Thank you.
