### ISSUE TITLE
wmin and wmax constraints in minCVaR are not hold

### ISSUE THREAD

**Issue by pgarnry** [enricoschumann/NMOF#3]
Hi Enrico,

Great package and appreciate your work a lot. I have noticed an issue when playing around with the minCVaR function. The function does not abide by its wmin and wmax constraints.

Here is a reproducible example.

```{r}
library(PerformanceAnalytics)
library(MNOF)
data(edhec)

opt <- NMOF::minCVaR(R = as.matrix(edhec), # return scenarios
                     q = 0.05, # tail-risk (CVaR level)
                     wmin = 0.05,
                     wmax = 0.2,
                     m = apply(edhec, 2, mean),
                     min.return = 0.05 / 12)

opt[1:ncol(edhec)]
```

![image](https://user-images.githubusercontent.com/9973866/108710028-c7b09900-7513-11eb-9ff9-e8c66cca72c3.png)

Best,
Peter

**Comment by enricoschumann** [comment]
Hi Peter,

thank you for the report.

I have updated the function, and min/max constraints  -- and group constraints as well -- should be supported now:

```r
library("PerformanceAnalytics")
library("NMOF")

opt <- NMOF::minCVaR(R = as.matrix(edhec), # return scenarios
                     q = 0.05, # tail-risk (CVaR level)
                     wmin = 0.05,
                     wmax = 0.2,
                     m = apply(edhec, 2, mean),
                     min.return = 0.05 / 12)
c(opt)
## [1] 0.050000 0.050000 0.050000 0.050000 0.152534
## [6] 0.050000 0.050000 0.050000 0.050000 0.200000
##[11] 0.050000 0.147466 0.050000
```

You can either use the version from GitHub or the one at http://enricoschumann.net/R/packages/NMOF/index.htm .
Would you give it a try, please? 

Again, thank you for the report.

**Comment by pgarnry** [comment]
Hi Enrico,

It works perfectly. Thanks for changing it so quickly.

Best,
Peter

**Comment by pgarnry** [comment]
Hi Enrico,

It works perfectly. Thanks for changing it so quickly.

Best,
Peter
